CANDIDATES = [
    "ANO_ELEICAO",
    "NUM_TURNO",
    "DESCRICAO_ELEICAO",
    "SIGLA_UF",
    "SIGLA_UE",
    "DESCRICAO_UE",
    "CODIGO_CARGO",
    "DESCRICAO_CARGO",
    "NOME_CANDIDATO",
    "SEQUENCIAL_CANDIDATO",
    "NUMERO_CANDIDATO",
    "CPF_CANDIDATO",
    "NOME_URNA_CANDIDATO",
    "COD_SITUACAO_CANDIDATURA",
    "DES_SITUACAO_CANDIDATURA",
    "NUMERO_PARTIDO",
    "SIGLA_PARTIDO",
    "NOME_PARTIDO",
    "CODIGO_LEGENDA",
    "SIGLA_LEGENDA",
    "COMPOSICAO_LEGENDA",
    "NOME_COLIGACAO",
    "CODIGO_OCUPACAO",
    "DESCRICAO_OCUPACAO",
    "DATA_NASCIMENTO",
    "NUM_TITULO_ELEITORAL_CANDIDATO",
    "IDADE_DATA_ELEICAO",
    "CODIGO_SEXO",
    "DESCRICAO_SEXO",
    "COD_GRAU_INSTRUCAO",
    "DESCRICAO_GRAU_INSTRUCAO",
    "CODIGO_ESTADO_CIVIL",
    "DESCRICAO_ESTADO_CIVIL",
    "CODIGO_COR_RACA",
    "DESCRICAO_COR_RACA",
    "CODIGO_NACIONALIDADE",
    "DESCRICAO_NACIONALIDADE",
    "SIGLA_UF_NASCIMENTO",
    "CODIGO_MUNICIPIO_NASCIMENTO",
    "NOME_MUNICIPIO_NASCIMENTO",
    "DESPESA_MAX_CAMPANHA",
    "COD_SIT_TOT_TURNO",
    "DESC_SIT_TOT_TURNO",
    "EMAIL_CANDIDATO"
]

PARTIES = [
    "ANO_ELEICAO",
    "CODIGO_CARGO",
    "COMPOSICAO_COLIGACAO",
    "DATA_GERACAO",
    "DESCRICAO_CARGO",
    "DESCRICAO_ELEICAO",
    "DESCRICAO_UE",
    "HORA_GERACAO",
    "NOME_COLIGACAO",
    "NOME_PARTIDO",
    "NUMERO_PARTIDO",
    "NUM_TURNO",
    "SEQUENCIA_COLIGACAO",
    "SIGLA_COLIGACAO",
    "SIGLA_PARTIDO",
    "SIGLA_UE",
    "SIGLA_UF",
    "TIPO_LEGENDA"
]

VOTES = {

    # BR
    0: [
        "ANO_ELEICAO",
        "NUM_TURNO",
        "DESCRICAO_ELEICAO",
        "CODIGO_CARGO",
        "DESCRICAO_CARGO",
        "NUMERO_CANDIDATO",
        "QTDE_VOTOS"
    ],

    # MACRO
    1: [
        "ANO_ELEICAO",
        "CODIGO_MACRO",
        "NOME_MACRO",
        "NUM_TURNO",
        "DESCRICAO_ELEICAO",
        "CODIGO_CARGO",
        "DESCRICAO_CARGO",
        "NUMERO_CANDIDATO",
        "QTDE_VOTOS"
    ],

    # UF
    2: [
        "ANO_ELEICAO",
        "UF",
        "NOME_UF",
        "CODIGO_MACRO",
        "NOME_MACRO",
        "SIGLA_UE",
        "NUM_TURNO",
        "DESCRICAO_ELEICAO",
        "CODIGO_CARGO",
        "DESCRICAO_CARGO",
        "NUMERO_CANDIDATO",
        "QTDE_VOTOS"
    ],

    # MESO
    4: [
        "ANO_ELEICAO",
        "CODIGO_MESO",
        "NOME_MESO",
        "UF",
        "NOME_UF",
        "CODIGO_MACRO",
        "NOME_MACRO",
        "SIGLA_UE",
        "NUM_TURNO",
        "DESCRICAO_ELEICAO",
        "CODIGO_CARGO",
        "DESCRICAO_CARGO",
        "NUMERO_CANDIDATO",
        "QTDE_VOTOS"
    ],

    # MICRO
    5: [
        "ANO_ELEICAO",
        "CODIGO_MICRO",
        "NOME_MICRO",
        "CODIGO_MESO",
        "NOME_MESO",
        "UF",
        "NOME_UF",
        "CODIGO_MACRO",
        "NOME_MACRO",
        "SIGLA_UE",
        "NUM_TURNO",
        "DESCRICAO_ELEICAO",
        "CODIGO_CARGO",
        "DESCRICAO_CARGO",
        "NUMERO_CANDIDATO",
        "QTDE_VOTOS"
    ],

    # MUNICIPIO
    6: [
        "ANO_ELEICAO",
        "COD_MUN_TSE",
        "COD_MUN_IBGE",
        "NOME_MUNICIPIO",
        "CODIGO_MICRO",
        "NOME_MICRO",
        "CODIGO_MESO",
        "NOME_MESO",
        "UF",
        "NOME_UF",
        "CODIGO_MACRO",
        "NOME_MACRO",
        "SIGLA_UE",
        "NUM_TURNO",
        "DESCRICAO_ELEICAO",
        "CODIGO_CARGO",
        "DESCRICAO_CARGO",
        "NUMERO_CANDIDATO",
        "QTDE_VOTOS"
    ],

    # MUNZONA
    7: [
        "ANO_ELEICAO",
        "NUM_ZONA",
        "COD_MUN_TSE",
        "COD_MUN_IBGE",
        "NOME_MUNICIPIO",
        "CODIGO_MICRO",
        "NOME_MICRO",
        "CODIGO_MESO",
        "NOME_MESO",
        "UF",
        "NOME_UF",
        "CODIGO_MACRO",
        "NOME_MACRO",
        "SIGLA_UE",
        "NUM_TURNO",
        "DESCRICAO_ELEICAO",
        "CODIGO_CARGO",
        "DESCRICAO_CARGO",
        "NUMERO_CANDIDATO",
        "QTDE_VOTOS"
    ],

    # ZONA
    8: [
        "ANO_ELEICAO",
        "NUM_ZONA",
        "CODIGO_MICRO",
        "NOME_MICRO",
        "CODIGO_MESO",
        "NOME_MESO",
        "UF",
        "NOME_UF",
        "CODIGO_MACRO",
        "NOME_MACRO",
        "SIGLA_UE",
        "NUM_TURNO",
        "DESCRICAO_ELEICAO",
        "CODIGO_CARGO",
        "DESCRICAO_CARGO",
        "NUMERO_CANDIDATO",
        "QTDE_VOTOS"
    ],

    # VOTACAO SECAO
    9: [
        "ANO_ELEICAO",
        "NUM_SECAO",
        "NUM_ZONA",
        "CODIGO_MICRO",
        "NOME_MICRO",
        "CODIGO_MESO",
        "NOME_MESO",
        "UF",
        "NOME_UF",
        "CODIGO_MACRO",
        "NOME_MACRO",
        "COD_MUN_TSE",
        "COD_MUN_IBGE",
        "NOME_MUNICIPIO",
        "NUM_TURNO",
        "DESCRICAO_ELEICAO",
        "SIGLA_UE",
        "CODIGO_CARGO",
        "DESCRICAO_CARGO",
        "NUMERO_CANDIDATO",
        "QTDE_VOTOS"
    ],

    # LOCAL VOTACAO
    10: [
        "ANO_ELEICAO",
        "NUM_ZONA",
        "CODIGO_MICRO",
        "NOME_MICRO",
        "CODIGO_MESO",
        "NOME_MESO",
        "UF",
        "NOME_UF",
        "CODIGO_MACRO",
        "NOME_MACRO",
        "COD_MUN_TSE",
        "COD_MUN_IBGE",
        "NOME_MUNICIPIO",
        "NUM_TURNO",
        "DESCRICAO_ELEICAO",
        "SIGLA_UE",
        "CODIGO_CARGO",
        "DESCRICAO_CARGO",
        "NUMERO_CANDIDATO",
        "NOME_LOCAL_VOTACAO",
        "NUM_LOCAL_VOTACAO",
        "DESCRICAO_ENDERECO",
        "DESCRICAO_BAIRRO",
        "NUM_CEP",
        "NOME_LOCALIDADE",
        "QTDE_VOTOS"
    ]

}

CANDIDATE_VOTES = {

    # BR
    0: [
        "ANO_ELEICAO",
        "NUM_TURNO",
        "DESCRICAO_ELEICAO",
        "CODIGO_CARGO",
        "DESCRICAO_CARGO",
        "NOME_CANDIDATO",
        "NUMERO_CANDIDATO",
        "CPF_CANDIDATO",
        "NOME_URNA_CANDIDATO",
        "COD_SITUACAO_CANDIDATURA",
        "DES_SITUACAO_CANDIDATURA",
        "NUMERO_PARTIDO",
        "SIGLA_PARTIDO",
        "NOME_PARTIDO",
        "CODIGO_LEGENDA",
        "SIGLA_LEGENDA",
        "COMPOSICAO_LEGENDA",
        "CODIGO_OCUPACAO",
        "DESCRICAO_OCUPACAO",
        "DATA_NASCIMENTO",
        "NUM_TITULO_ELEITORAL_CANDIDATO",
        "IDADE_DATA_ELEICAO",
        "CODIGO_SEXO",
        "DESCRICAO_SEXO",
        "COD_GRAU_INSTRUCAO",
        "DESCRICAO_GRAU_INSTRUCAO",
        "CODIGO_ESTADO_CIVIL",
        "DESCRICAO_ESTADO_CIVIL",
        "CODIGO_COR_RACA",
        "DESCRICAO_COR_RACA",
        "CODIGO_NACIONALIDADE",
        "DESCRICAO_NACIONALIDADE",
        "SIGLA_UF_NASCIMENTO",
        "CODIGO_MUNICIPIO_NASCIMENTO",
        "NOME_MUNICIPIO_NASCIMENTO",
        "DESPESA_MAX_CAMPANHA",
        "COD_SIT_TOT_TURNO",
        "DESC_SIT_TOT_TURNO",
        "EMAIL_CANDIDATO",
        "TIPO_LEGENDA",
        "SIGLA_COLIGACAO",
        "NOME_COLIGACAO",
        "COMPOSICAO_COLIGACAO",
        "QTDE_VOTOS"
    ],

    # MACRO
    1: [
        "ANO_ELEICAO",
        "NUM_TURNO",
        "CODIGO_MACRO",
        "NOME_MACRO",
        "DESCRICAO_ELEICAO",
        "CODIGO_CARGO",
        "DESCRICAO_CARGO",
        "NOME_CANDIDATO",
        "NUMERO_CANDIDATO",
        "CPF_CANDIDATO",
        "NOME_URNA_CANDIDATO",
        "COD_SITUACAO_CANDIDATURA",
        "DES_SITUACAO_CANDIDATURA",
        "NUMERO_PARTIDO",
        "SIGLA_PARTIDO",
        "NOME_PARTIDO",
        "CODIGO_LEGENDA",
        "SIGLA_LEGENDA",
        "COMPOSICAO_LEGENDA",
        "CODIGO_OCUPACAO",
        "DESCRICAO_OCUPACAO",
        "DATA_NASCIMENTO",
        "NUM_TITULO_ELEITORAL_CANDIDATO",
        "IDADE_DATA_ELEICAO",
        "CODIGO_SEXO",
        "DESCRICAO_SEXO",
        "COD_GRAU_INSTRUCAO",
        "DESCRICAO_GRAU_INSTRUCAO",
        "CODIGO_ESTADO_CIVIL",
        "DESCRICAO_ESTADO_CIVIL",
        "CODIGO_COR_RACA",
        "DESCRICAO_COR_RACA",
        "CODIGO_NACIONALIDADE",
        "DESCRICAO_NACIONALIDADE",
        "SIGLA_UF_NASCIMENTO",
        "CODIGO_MUNICIPIO_NASCIMENTO",
        "NOME_MUNICIPIO_NASCIMENTO",
        "DESPESA_MAX_CAMPANHA",
        "COD_SIT_TOT_TURNO",
        "DESC_SIT_TOT_TURNO",
        "EMAIL_CANDIDATO",
        "TIPO_LEGENDA",
        "SIGLA_COLIGACAO",
        "NOME_COLIGACAO",
        "COMPOSICAO_COLIGACAO",
        "QTDE_VOTOS"
    ],

    # UF
    2: [
        "ANO_ELEICAO",
        "NUM_TURNO",
        "UF",
        "NOME_UF",
        "CODIGO_MACRO",
        "NOME_MACRO",
        "DESCRICAO_ELEICAO",
        "SIGLA_UE",
        "DESCRICAO_UE",
        "CODIGO_CARGO",
        "DESCRICAO_CARGO",
        "NOME_CANDIDATO",
        "NUMERO_CANDIDATO",
        "CPF_CANDIDATO",
        "NOME_URNA_CANDIDATO",
        "COD_SITUACAO_CANDIDATURA",
        "DES_SITUACAO_CANDIDATURA",
        "NUMERO_PARTIDO",
        "SIGLA_PARTIDO",
        "NOME_PARTIDO",
        "CODIGO_LEGENDA",
        "SIGLA_LEGENDA",
        "COMPOSICAO_LEGENDA",
        "CODIGO_OCUPACAO",
        "DESCRICAO_OCUPACAO",
        "DATA_NASCIMENTO",
        "NUM_TITULO_ELEITORAL_CANDIDATO",
        "IDADE_DATA_ELEICAO",
        "CODIGO_SEXO",
        "DESCRICAO_SEXO",
        "COD_GRAU_INSTRUCAO",
        "DESCRICAO_GRAU_INSTRUCAO",
        "CODIGO_ESTADO_CIVIL",
        "DESCRICAO_ESTADO_CIVIL",
        "CODIGO_COR_RACA",
        "DESCRICAO_COR_RACA",
        "CODIGO_NACIONALIDADE",
        "DESCRICAO_NACIONALIDADE",
        "SIGLA_UF_NASCIMENTO",
        "CODIGO_MUNICIPIO_NASCIMENTO",
        "NOME_MUNICIPIO_NASCIMENTO",
        "DESPESA_MAX_CAMPANHA",
        "COD_SIT_TOT_TURNO",
        "DESC_SIT_TOT_TURNO",
        "EMAIL_CANDIDATO",
        "TIPO_LEGENDA",
        "SIGLA_COLIGACAO",
        "NOME_COLIGACAO",
        "COMPOSICAO_COLIGACAO",
        "QTDE_VOTOS"
    ],

    # MESO
    4: [
        "ANO_ELEICAO",
        "NUM_TURNO",
        "CODIGO_MESO",
        "NOME_MESO",
        "CODIGO_MACRO",
        "NOME_MACRO",
        "UF",
        "NOME_UF",
        "DESCRICAO_ELEICAO",
        "SIGLA_UE",
        "DESCRICAO_UE",
        "CODIGO_CARGO",
        "DESCRICAO_CARGO",
        "NOME_CANDIDATO",
        "NUMERO_CANDIDATO",
        "CPF_CANDIDATO",
        "NOME_URNA_CANDIDATO",
        "COD_SITUACAO_CANDIDATURA",
        "DES_SITUACAO_CANDIDATURA",
        "NUMERO_PARTIDO",
        "SIGLA_PARTIDO",
        "NOME_PARTIDO",
        "CODIGO_LEGENDA",
        "SIGLA_LEGENDA",
        "COMPOSICAO_LEGENDA",
        "CODIGO_OCUPACAO",
        "DESCRICAO_OCUPACAO",
        "DATA_NASCIMENTO",
        "NUM_TITULO_ELEITORAL_CANDIDATO",
        "IDADE_DATA_ELEICAO",
        "CODIGO_SEXO",
        "DESCRICAO_SEXO",
        "COD_GRAU_INSTRUCAO",
        "DESCRICAO_GRAU_INSTRUCAO",
        "CODIGO_ESTADO_CIVIL",
        "DESCRICAO_ESTADO_CIVIL",
        "CODIGO_COR_RACA",
        "DESCRICAO_COR_RACA",
        "CODIGO_NACIONALIDADE",
        "DESCRICAO_NACIONALIDADE",
        "SIGLA_UF_NASCIMENTO",
        "CODIGO_MUNICIPIO_NASCIMENTO",
        "NOME_MUNICIPIO_NASCIMENTO",
        "DESPESA_MAX_CAMPANHA",
        "COD_SIT_TOT_TURNO",
        "DESC_SIT_TOT_TURNO",
        "EMAIL_CANDIDATO",
        "TIPO_LEGENDA",
        "SIGLA_COLIGACAO",
        "NOME_COLIGACAO",
        "COMPOSICAO_COLIGACAO",
        "QTDE_VOTOS"
    ],

    # MICRO
    5: [
        "ANO_ELEICAO",
        "NUM_TURNO",
        "CODIGO_MICRO",
        "NOME_MICRO",
        "CODIGO_MESO",
        "NOME_MESO",
        "UF",
        "NOME_UF",
        "CODIGO_MACRO",
        "NOME_MACRO",
        "DESCRICAO_ELEICAO",
        "SIGLA_UE",
        "DESCRICAO_UE",
        "CODIGO_CARGO",
        "DESCRICAO_CARGO",
        "NOME_CANDIDATO",
        "NUMERO_CANDIDATO",
        "CPF_CANDIDATO",
        "NOME_URNA_CANDIDATO",
        "COD_SITUACAO_CANDIDATURA",
        "DES_SITUACAO_CANDIDATURA",
        "NUMERO_PARTIDO",
        "SIGLA_PARTIDO",
        "NOME_PARTIDO",
        "CODIGO_LEGENDA",
        "SIGLA_LEGENDA",
        "COMPOSICAO_LEGENDA",
        "CODIGO_OCUPACAO",
        "DESCRICAO_OCUPACAO",
        "DATA_NASCIMENTO",
        "NUM_TITULO_ELEITORAL_CANDIDATO",
        "IDADE_DATA_ELEICAO",
        "CODIGO_SEXO",
        "DESCRICAO_SEXO",
        "COD_GRAU_INSTRUCAO",
        "DESCRICAO_GRAU_INSTRUCAO",
        "CODIGO_ESTADO_CIVIL",
        "DESCRICAO_ESTADO_CIVIL",
        "CODIGO_COR_RACA",
        "DESCRICAO_COR_RACA",
        "CODIGO_NACIONALIDADE",
        "DESCRICAO_NACIONALIDADE",
        "SIGLA_UF_NASCIMENTO",
        "CODIGO_MUNICIPIO_NASCIMENTO",
        "NOME_MUNICIPIO_NASCIMENTO",
        "DESPESA_MAX_CAMPANHA",
        "COD_SIT_TOT_TURNO",
        "DESC_SIT_TOT_TURNO",
        "EMAIL_CANDIDATO",
        "TIPO_LEGENDA",
        "SIGLA_COLIGACAO",
        "NOME_COLIGACAO",
        "COMPOSICAO_COLIGACAO",
        "QTDE_VOTOS"
    ],

    # MUNICIPIO
    6: [
        "ANO_ELEICAO",
        "NUM_TURNO",
        "COD_MUN_TSE",
        "COD_MUN_IBGE",
        "NOME_MUNICIPIO",
        "CODIGO_MICRO",
        "NOME_MICRO",
        "CODIGO_MESO",
        "NOME_MESO",
        "UF",
        "NOME_UF",
        "CODIGO_MACRO",
        "NOME_MACRO",
        "DESCRICAO_ELEICAO",
        "SIGLA_UE",
        "DESCRICAO_UE",
        "CODIGO_CARGO",
        "DESCRICAO_CARGO",
        "NOME_CANDIDATO",
        "NUMERO_CANDIDATO",
        "CPF_CANDIDATO",
        "NOME_URNA_CANDIDATO",
        "COD_SITUACAO_CANDIDATURA",
        "DES_SITUACAO_CANDIDATURA",
        "NUMERO_PARTIDO",
        "SIGLA_PARTIDO",
        "NOME_PARTIDO",
        "CODIGO_LEGENDA",
        "SIGLA_LEGENDA",
        "COMPOSICAO_LEGENDA",
        "CODIGO_OCUPACAO",
        "DESCRICAO_OCUPACAO",
        "DATA_NASCIMENTO",
        "NUM_TITULO_ELEITORAL_CANDIDATO",
        "IDADE_DATA_ELEICAO",
        "CODIGO_SEXO",
        "DESCRICAO_SEXO",
        "COD_GRAU_INSTRUCAO",
        "DESCRICAO_GRAU_INSTRUCAO",
        "CODIGO_ESTADO_CIVIL",
        "DESCRICAO_ESTADO_CIVIL",
        "CODIGO_COR_RACA",
        "DESCRICAO_COR_RACA",
        "CODIGO_NACIONALIDADE",
        "DESCRICAO_NACIONALIDADE",
        "SIGLA_UF_NASCIMENTO",
        "CODIGO_MUNICIPIO_NASCIMENTO",
        "NOME_MUNICIPIO_NASCIMENTO",
        "DESPESA_MAX_CAMPANHA",
        "COD_SIT_TOT_TURNO",
        "DESC_SIT_TOT_TURNO",
        "EMAIL_CANDIDATO",
        "TIPO_LEGENDA",
        "SIGLA_COLIGACAO",
        "NOME_COLIGACAO",
        "COMPOSICAO_COLIGACAO",
        "QTDE_VOTOS"
    ],

    # MUNZONA
    7: [
        "ANO_ELEICAO",
        "NUM_TURNO",
        "COD_MUN_TSE",
        "COD_MUN_IBGE",
        "NOME_MUNICIPIO",
        "NUM_ZONA",
        "CODIGO_MICRO",
        "NOME_MICRO",
        "CODIGO_MESO",
        "NOME_MESO",
        "UF",
        "NOME_UF",
        "CODIGO_MACRO",
        "NOME_MACRO",
        "DESCRICAO_ELEICAO",
        "SIGLA_UE",
        "DESCRICAO_UE",
        "CODIGO_CARGO",
        "DESCRICAO_CARGO",
        "NOME_CANDIDATO",
        "NUMERO_CANDIDATO",
        "CPF_CANDIDATO",
        "NOME_URNA_CANDIDATO",
        "COD_SITUACAO_CANDIDATURA",
        "DES_SITUACAO_CANDIDATURA",
        "NUMERO_PARTIDO",
        "SIGLA_PARTIDO",
        "NOME_PARTIDO",
        "CODIGO_LEGENDA",
        "SIGLA_LEGENDA",
        "COMPOSICAO_LEGENDA",
        "CODIGO_OCUPACAO",
        "DESCRICAO_OCUPACAO",
        "DATA_NASCIMENTO",
        "NUM_TITULO_ELEITORAL_CANDIDATO",
        "IDADE_DATA_ELEICAO",
        "CODIGO_SEXO",
        "DESCRICAO_SEXO",
        "COD_GRAU_INSTRUCAO",
        "DESCRICAO_GRAU_INSTRUCAO",
        "CODIGO_ESTADO_CIVIL",
        "DESCRICAO_ESTADO_CIVIL",
        "CODIGO_COR_RACA",
        "DESCRICAO_COR_RACA",
        "CODIGO_NACIONALIDADE",
        "DESCRICAO_NACIONALIDADE",
        "SIGLA_UF_NASCIMENTO",
        "CODIGO_MUNICIPIO_NASCIMENTO",
        "NOME_MUNICIPIO_NASCIMENTO",
        "DESPESA_MAX_CAMPANHA",
        "COD_SIT_TOT_TURNO",
        "DESC_SIT_TOT_TURNO",
        "EMAIL_CANDIDATO",
        "TIPO_LEGENDA",
        "SIGLA_COLIGACAO",
        "NOME_COLIGACAO",
        "COMPOSICAO_COLIGACAO",
        "QTDE_VOTOS"
    ],

    # ZONA
    8: [
        "ANO_ELEICAO",
        "NUM_TURNO",
        "NUM_ZONA",
        "CODIGO_MICRO",
        "NOME_MICRO",
        "CODIGO_MESO",
        "NOME_MESO",
        "UF",
        "NOME_UF",
        "CODIGO_MACRO",
        "NOME_MACRO",
        "DESCRICAO_ELEICAO",
        "SIGLA_UE",
        "DESCRICAO_UE",
        "CODIGO_CARGO",
        "DESCRICAO_CARGO",
        "NOME_CANDIDATO",
        "NUMERO_CANDIDATO",
        "CPF_CANDIDATO",
        "NOME_URNA_CANDIDATO",
        "COD_SITUACAO_CANDIDATURA",
        "DES_SITUACAO_CANDIDATURA",
        "NUMERO_PARTIDO",
        "SIGLA_PARTIDO",
        "NOME_PARTIDO",
        "CODIGO_LEGENDA",
        "SIGLA_LEGENDA",
        "COMPOSICAO_LEGENDA",
        "CODIGO_OCUPACAO",
        "DESCRICAO_OCUPACAO",
        "DATA_NASCIMENTO",
        "NUM_TITULO_ELEITORAL_CANDIDATO",
        "IDADE_DATA_ELEICAO",
        "CODIGO_SEXO",
        "DESCRICAO_SEXO",
        "COD_GRAU_INSTRUCAO",
        "DESCRICAO_GRAU_INSTRUCAO",
        "CODIGO_ESTADO_CIVIL",
        "DESCRICAO_ESTADO_CIVIL",
        "CODIGO_COR_RACA",
        "DESCRICAO_COR_RACA",
        "CODIGO_NACIONALIDADE",
        "DESCRICAO_NACIONALIDADE",
        "SIGLA_UF_NASCIMENTO",
        "CODIGO_MUNICIPIO_NASCIMENTO",
        "NOME_MUNICIPIO_NASCIMENTO",
        "DESPESA_MAX_CAMPANHA",
        "COD_SIT_TOT_TURNO",
        "DESC_SIT_TOT_TURNO",
        "EMAIL_CANDIDATO",
        "TIPO_LEGENDA",
        "SIGLA_COLIGACAO",
        "NOME_COLIGACAO",
        "COMPOSICAO_COLIGACAO",
        "QTDE_VOTOS"
    ],

    9: [
        "ANO_ELEICAO",
        "NUM_TURNO",
        "COD_MUN_TSE",
        "COD_MUN_IBGE",
        "NOME_MUNICIPIO",
        "NUM_ZONA",
        "NUM_SECAO",
        "CODIGO_MICRO",
        "NOME_MICRO",
        "CODIGO_MESO",
        "NOME_MESO",
        "UF",
        "NOME_UF",
        "CODIGO_MACRO",
        "NOME_MACRO",
        "DESCRICAO_ELEICAO",
        "SIGLA_UE",
        "DESCRICAO_UE",
        "CODIGO_CARGO",
        "DESCRICAO_CARGO",
        "NOME_CANDIDATO",
        "NUMERO_CANDIDATO",
        "CPF_CANDIDATO",
        "NOME_URNA_CANDIDATO",
        "COD_SITUACAO_CANDIDATURA",
        "DES_SITUACAO_CANDIDATURA",
        "NUMERO_PARTIDO",
        "SIGLA_PARTIDO",
        "NOME_PARTIDO",
        "CODIGO_LEGENDA",
        "SIGLA_LEGENDA",
        "COMPOSICAO_LEGENDA",
        "CODIGO_OCUPACAO",
        "DESCRICAO_OCUPACAO",
        "DATA_NASCIMENTO",
        "NUM_TITULO_ELEITORAL_CANDIDATO",
        "IDADE_DATA_ELEICAO",
        "CODIGO_SEXO",
        "DESCRICAO_SEXO",
        "COD_GRAU_INSTRUCAO",
        "DESCRICAO_GRAU_INSTRUCAO",
        "CODIGO_ESTADO_CIVIL",
        "DESCRICAO_ESTADO_CIVIL",
        "CODIGO_COR_RACA",
        "DESCRICAO_COR_RACA",
        "CODIGO_NACIONALIDADE",
        "DESCRICAO_NACIONALIDADE",
        "SIGLA_UF_NASCIMENTO",
        "CODIGO_MUNICIPIO_NASCIMENTO",
        "NOME_MUNICIPIO_NASCIMENTO",
        "DESPESA_MAX_CAMPANHA",
        "COD_SIT_TOT_TURNO",
        "DESC_SIT_TOT_TURNO",
        "EMAIL_CANDIDATO",
        "TIPO_LEGENDA",
        "SIGLA_COLIGACAO",
        "NOME_COLIGACAO",
        "COMPOSICAO_COLIGACAO",
        "QTDE_VOTOS"
    ]

}

PARTY_VOTES = {

    # BR
    0: [
        "ANO_ELEICAO",
        "NUM_TURNO",
        "DESCRICAO_ELEICAO",
        "SIGLA_UE",
        "DESCRICAO_UE",
        "CODIGO_CARGO",
        "DESCRICAO_CARGO",
        "NUMERO_PARTIDO",
        "SIGLA_PARTIDO",
        "NOME_PARTIDO",
        "QTDE_VOTOS",
    ],

    # MACRO
    1: [
        "ANO_ELEICAO",
        "NUM_TURNO",
        "CODIGO_MACRO",
        "NOME_MACRO",
        "DESCRICAO_ELEICAO",
        "CODIGO_CARGO",
        "DESCRICAO_CARGO",
        "NUMERO_PARTIDO",
        "SIGLA_PARTIDO",
        "NOME_PARTIDO",
        "QTDE_VOTOS",
    ],

    # UF
    2: [
        "ANO_ELEICAO",
        "NUM_TURNO",
        "UF",
        "NOME_UF",
        "CODIGO_MACRO",
        "NOME_MACRO",
        "DESCRICAO_ELEICAO",
        "SIGLA_UE",
        "DESCRICAO_UE",
        "CODIGO_CARGO",
        "DESCRICAO_CARGO",
        "NUMERO_PARTIDO",
        "SIGLA_PARTIDO",
        "NOME_PARTIDO",
        "QTDE_VOTOS",
    ],

    # MESO
    4: [
        "ANO_ELEICAO",
        "NUM_TURNO",
        "CODIGO_MESO",
        "NOME_MESO",
        "UF",
        "NOME_UF",
        "CODIGO_MACRO",
        "NOME_MACRO",
        "DESCRICAO_ELEICAO",
        "SIGLA_UE",
        "DESCRICAO_UE",
        "CODIGO_CARGO",
        "DESCRICAO_CARGO",
        "NUMERO_PARTIDO",
        "SIGLA_PARTIDO",
        "NOME_PARTIDO",
        "QTDE_VOTOS",
    ],

    # MICRO
    5: [
        "ANO_ELEICAO",
        "NUM_TURNO",
        "CODIGO_MICRO",
        "NOME_MICRO",
        "CODIGO_MESO",
        "NOME_MESO",
        "UF",
        "NOME_UF",
        "CODIGO_MACRO",
        "NOME_MACRO",
        "DESCRICAO_ELEICAO",
        "SIGLA_UE",
        "DESCRICAO_UE",
        "CODIGO_CARGO",
        "DESCRICAO_CARGO",
        "NUMERO_PARTIDO",
        "SIGLA_PARTIDO",
        "NOME_PARTIDO",
        "QTDE_VOTOS",
    ],

    # MUNICIPIO
    6: [
        "ANO_ELEICAO",
        "NUM_TURNO",
        "NUM_ZONA",
        "COD_MUN_TSE",
        "COD_MUN_IBGE",
        "NOME_MUNICIPIO",
        "CODIGO_MICRO",
        "NOME_MICRO",
        "CODIGO_MESO",
        "NOME_MESO",
        "UF",
        "NOME_UF",
        "CODIGO_MACRO",
        "NOME_MACRO",
        "DESCRICAO_ELEICAO",
        "SIGLA_UE",
        "DESCRICAO_UE",
        "CODIGO_CARGO",
        "DESCRICAO_CARGO",
        "NUMERO_PARTIDO",
        "SIGLA_PARTIDO",
        "NOME_PARTIDO",
        "QTDE_VOTOS",
    ],

    # munzona
    7: [
        "ANO_ELEICAO",
        "NUM_TURNO",
        "NUM_ZONA",
        "COD_MUN_TSE",
        "COD_MUN_IBGE",
        "NOME_MUNICIPIO",
        "CODIGO_MICRO",
        "NOME_MICRO",
        "CODIGO_MESO",
        "NOME_MESO",
        "UF",
        "NOME_UF",
        "CODIGO_MACRO",
        "NOME_MACRO",
        "DESCRICAO_ELEICAO",
        "SIGLA_UE",
        "DESCRICAO_UE",
        "CODIGO_CARGO",
        "DESCRICAO_CARGO",
        "NUMERO_PARTIDO",
        "SIGLA_PARTIDO",
        "NOME_PARTIDO",
        "QTDE_VOTOS",
    ],

    # zona
    8: [
        "ANO_ELEICAO",
        "NUM_TURNO",
        "NUM_ZONA",
        "CODIGO_MICRO",
        "NOME_MICRO",
        "CODIGO_MESO",
        "NOME_MESO",
        "UF",
        "NOME_UF",
        "CODIGO_MACRO",
        "NOME_MACRO",
        "DESCRICAO_ELEICAO",
        "SIGLA_UE",
        "DESCRICAO_UE",
        "CODIGO_CARGO",
        "DESCRICAO_CARGO",
        "NUMERO_PARTIDO",
        "SIGLA_PARTIDO",
        "NOME_PARTIDO",
        "QTDE_VOTOS",
    ],

    # VOTSEC
    9: [
        "ANO_ELEICAO",
        "NUM_TURNO",
        "NUM_ZONA",
        "NUM_SECAO",
        "COD_MUN_TSE",
        "COD_MUN_IBGE",
        "NOME_MUNICIPIO",
        "CODIGO_MICRO",
        "NOME_MICRO",
        "CODIGO_MESO",
        "NOME_MESO",
        "UF",
        "NOME_UF",
        "CODIGO_MACRO",
        "NOME_MACRO",
        "DESCRICAO_ELEICAO",
        "SIGLA_UE",
        "DESCRICAO_UE",
        "CODIGO_CARGO",
        "DESCRICAO_CARGO",
        "NUMERO_PARTIDO",
        "SIGLA_PARTIDO",
        "NOME_PARTIDO",
        "QTDE_VOTOS",
    ]

}

COALITION_VOTES = {

    # BR
    0: [
        "ANO_ELEICAO",
        "NUM_TURNO",
        "DESCRICAO_ELEICAO",
        "SIGLA_UE",
        "DESCRICAO_UE",
        "CODIGO_CARGO",
        "DESCRICAO_CARGO",
        "SIGLA_COLIGACAO",
        "NOME_COLIGACAO",
        "COMPOSICAO_COLIGACAO",
        "QTDE_VOTOS",
    ],

    # MACRO
    1: [
        "ANO_ELEICAO",
        "NUM_TURNO",
        "CODIGO_MACRO",
        "NOME_MACRO",
        "DESCRICAO_ELEICAO",
        "CODIGO_CARGO",
        "DESCRICAO_CARGO",
        "SIGLA_COLIGACAO",
        "NOME_COLIGACAO",
        "COMPOSICAO_COLIGACAO",
        "QTDE_VOTOS",
    ],

    # UF
    2: [
        "ANO_ELEICAO",
        "NUM_TURNO",
        "UF",
        "NOME_UF",
        "CODIGO_MACRO",
        "NOME_MACRO",
        "DESCRICAO_ELEICAO",
        "SIGLA_UE",
        "DESCRICAO_UE",
        "CODIGO_CARGO",
        "DESCRICAO_CARGO",
        "SIGLA_COLIGACAO",
        "NOME_COLIGACAO",
        "COMPOSICAO_COLIGACAO",
        "QTDE_VOTOS",
    ],

    # MESO
    4: [
        "ANO_ELEICAO",
        "NUM_TURNO",
        "UF",
        "NOME_UF",
        "CODIGO_MESO",
        "NOME_MESO",
        "CODIGO_MACRO",
        "NOME_MACRO",
        "DESCRICAO_ELEICAO",
        "SIGLA_UE",
        "DESCRICAO_UE",
        "CODIGO_CARGO",
        "DESCRICAO_CARGO",
        "SIGLA_COLIGACAO",
        "NOME_COLIGACAO",
        "COMPOSICAO_COLIGACAO",
        "QTDE_VOTOS",
    ],

    # MICRO
    5: [
        "ANO_ELEICAO",
        "NUM_TURNO",
        "CODIGO_MICRO",
        "NOME_MICRO",
        "CODIGO_MESO",
        "NOME_MESO",
        "UF",
        "NOME_UF",
        "CODIGO_MACRO",
        "NOME_MACRO",
        "DESCRICAO_ELEICAO",
        "SIGLA_UE",
        "DESCRICAO_UE",
        "CODIGO_CARGO",
        "DESCRICAO_CARGO",
        "SIGLA_COLIGACAO",
        "NOME_COLIGACAO",
        "COMPOSICAO_COLIGACAO",
        "QTDE_VOTOS",
    ],

    # MUNICIPIO
    6: [
        "ANO_ELEICAO",
        "NUM_TURNO",
        "COD_MUN_TSE",
        "COD_MUN_IBGE",
        "NOME_MUNICIPIO",
        "CODIGO_MICRO",
        "NOME_MICRO",
        "CODIGO_MESO",
        "NOME_MESO",
        "UF",
        "NOME_UF",
        "CODIGO_MACRO",
        "NOME_MACRO",
        "DESCRICAO_ELEICAO",
        "SIGLA_UE",
        "DESCRICAO_UE",
        "CODIGO_CARGO",
        "DESCRICAO_CARGO",
        "SIGLA_COLIGACAO",
        "NOME_COLIGACAO",
        "COMPOSICAO_COLIGACAO",
        "QTDE_VOTOS",
    ],

    # MUNZONA
    7: [
        "ANO_ELEICAO",
        "NUM_TURNO",
        "NUM_ZONA",
        "COD_MUN_TSE",
        "NOME_MUNICIPIO",
        "CODIGO_MICRO",
        "NOME_MICRO",
        "CODIGO_MESO",
        "NOME_MESO",
        "UF",
        "NOME_UF",
        "CODIGO_MACRO",
        "NOME_MACRO",
        "DESCRICAO_ELEICAO",
        "SIGLA_UE",
        "DESCRICAO_UE",
        "CODIGO_CARGO",
        "DESCRICAO_CARGO",
        "SIGLA_COLIGACAO",
        "NOME_COLIGACAO",
        "COMPOSICAO_COLIGACAO",
        "QTDE_VOTOS",
    ],

    # ZONA
    8: [
        "ANO_ELEICAO",
        "NUM_TURNO",
        "NUM_ZONA",
        "CODIGO_MICRO",
        "NOME_MICRO",
        "CODIGO_MESO",
        "NOME_MESO",
        "UF",
        "NOME_UF",
        "CODIGO_MACRO",
        "NOME_MACRO",
        "DESCRICAO_ELEICAO",
        "SIGLA_UE",
        "DESCRICAO_UE",
        "CODIGO_CARGO",
        "DESCRICAO_CARGO",
        "SIGLA_COLIGACAO",
        "NOME_COLIGACAO",
        "COMPOSICAO_COLIGACAO",
        "QTDE_VOTOS",
    ],

    # VOTSEC
    9: [
        "ANO_ELEICAO",
        "NUM_TURNO",
        "NUM_ZONA",
        "NUM_SECAO",
        "COD_MUN_TSE",
        "NOME_MUNICIPIO",
        "CODIGO_MICRO",
        "NOME_MICRO",
        "CODIGO_MESO",
        "NOME_MESO",
        "UF",
        "NOME_UF",
        "CODIGO_MACRO",
        "NOME_MACRO",
        "DESCRICAO_ELEICAO",
        "SIGLA_UE",
        "DESCRICAO_UE",
        "CODIGO_CARGO",
        "DESCRICAO_CARGO",
        "SIGLA_COLIGACAO",
        "NOME_COLIGACAO",
        "COMPOSICAO_COLIGACAO",
        "QTDE_VOTOS",
    ]

}

ELECTION_DETAILS = {

    # BR
    0: [
        "ANO_ELEICAO",
        "NUM_TURNO",
        "DESCRICAO_ELEICAO",
        "CODIGO_CARGO",
        "DESCRICAO_CARGO",
        "QTD_APTOS",
        "QTD_COMPARECIMENTO",
        "QTD_ABSTENCOES",
        "QT_VOTOS_NOMINAIS",
        "QT_VOTOS_BRANCOS",
        "QT_VOTOS_NULOS",
        "QT_VOTOS_LEGENDA",
        "QT_VOTOS_ANULADOS_APU_SEP"
    ],

    # MACRO
    1: [
        "ANO_ELEICAO",
        "NUM_TURNO",
        "CODIGO_MACRO",
        "NOME_MACRO",
        "DESCRICAO_ELEICAO",
        "CODIGO_CARGO",
        "DESCRICAO_CARGO",
        "QTD_APTOS",
        "QTD_COMPARECIMENTO",
        "QTD_ABSTENCOES",
        "QT_VOTOS_NOMINAIS",
        "QT_VOTOS_BRANCOS",
        "QT_VOTOS_NULOS",
        "QT_VOTOS_LEGENDA",
        "QT_VOTOS_ANULADOS_APU_SEP",
    ],

    # UF
    2: [
        "ANO_ELEICAO",
        "NUM_TURNO",
        "UF",
        "NOME_UF"
        "CODIGO_MACRO",
        "NOME_MACRO",
        "DESCRICAO_ELEICAO",
        "CODIGO_CARGO",
        "DESCRICAO_CARGO",
        "QTD_APTOS",
        "QTD_COMPARECIMENTO",
        "QTD_ABSTENCOES",
        "QT_VOTOS_NOMINAIS",
        "QT_VOTOS_BRANCOS",
        "QT_VOTOS_NULOS",
        "QT_VOTOS_LEGENDA",
        "QT_VOTOS_ANULADOS_APU_SEP",
    ],

    # MESO
    4: [
        "ANO_ELEICAO",
        "NUM_TURNO",
        "CODIGO_MESO",
        "NOME_MESO"
        "UF",
        "NOME_UF",
        "CODIGO_MACRO",
        "NOME_MACRO",
        "DESCRICAO_ELEICAO",
        "CODIGO_CARGO",
        "DESCRICAO_CARGO",
        "QTD_APTOS",
        "QTD_COMPARECIMENTO",
        "QTD_ABSTENCOES",
        "QT_VOTOS_NOMINAIS",
        "QT_VOTOS_BRANCOS",
        "QT_VOTOS_NULOS",
        "QT_VOTOS_LEGENDA",
        "QT_VOTOS_ANULADOS_APU_SEP",
    ],

    # MICRO
    5: [
        "ANO_ELEICAO",
        "NUM_TURNO",
        "CODIGO_MICRO",
        "NOME_MICRO",
        "CODIGO_MESO",
        "NOME_MESO",
        "UF",
        "NOME_UF",
        "CODIGO_MACRO",
        "NOME_MACRO",
        "DESCRICAO_ELEICAO",
        "CODIGO_CARGO",
        "DESCRICAO_CARGO",
        "QTD_APTOS",
        "QTD_COMPARECIMENTO",
        "QTD_ABSTENCOES",
        "QT_VOTOS_NOMINAIS",
        "QT_VOTOS_BRANCOS",
        "QT_VOTOS_NULOS",
        "QT_VOTOS_LEGENDA",
        "QT_VOTOS_ANULADOS_APU_SEP",
    ],

    # MUNICIPIO
    6: [
        "ANO_ELEICAO",
        "NUM_TURNO",
        "COD_MUN_TSE",
        "COD_MUN_IBGE",
        "NOME_MUNICIPIO",
        "CODIGO_MICRO",
        "NOME_MICRO",
        "CODIGO_MESO",
        "NOME_MESO",
        "UF",
        "NOME_UF",
        "CODIGO_MACRO",
        "NOME_MACRO",
        "DESCRICAO_ELEICAO",
        "CODIGO_CARGO",
        "DESCRICAO_CARGO",
        "QTD_APTOS",
        "QTD_COMPARECIMENTO",
        "QTD_ABSTENCOES",
        "QT_VOTOS_NOMINAIS",
        "QT_VOTOS_BRANCOS",
        "QT_VOTOS_NULOS",
        "QT_VOTOS_LEGENDA",
        "QT_VOTOS_ANULADOS_APU_SEP",
    ],

    # MUNZONA
    7: [
        "ANO_ELEICAO",
        "NUM_TURNO",
        "NUM_ZONA",
        "COD_MUN_TSE",
        "COD_MUN_IBGE",
        "NOME_MUNICIPIO",
        "CODIGO_MICRO",
        "NOME_MICRO",
        "CODIGO_MESO",
        "NOME_MESO",
        "UF",
        "NOME_UF",
        "CODIGO_MACRO",
        "NOME_MACRO",
        "DESCRICAO_ELEICAO",
        "CODIGO_CARGO",
        "DESCRICAO_CARGO",
        "QTD_APTOS",
        "QTD_COMPARECIMENTO",
        "QTD_ABSTENCOES",
        "QT_VOTOS_NOMINAIS",
        "QT_VOTOS_BRANCOS",
        "QT_VOTOS_NULOS",
        "QT_VOTOS_LEGENDA",
        "QT_VOTOS_ANULADOS_APU_SEP",
    ],

    # ZONA
    8: [
        "ANO_ELEICAO",
        "NUM_TURNO",
        "NUM_ZONA",
        "CODIGO_MICRO",
        "NOME_MICRO",
        "CODIGO_MESO",
        "NOME_MESO",
        "UF",
        "NOME_UF",
        "CODIGO_MACRO",
        "NOME_MACRO",
        "DESCRICAO_ELEICAO",
        "CODIGO_CARGO",
        "DESCRICAO_CARGO",
        "QTD_APTOS",
        "QTD_COMPARECIMENTO",
        "QTD_ABSTENCOES",
        "QT_VOTOS_NOMINAIS",
        "QT_VOTOS_BRANCOS",
        "QT_VOTOS_NULOS",
        "QT_VOTOS_LEGENDA",
        "QT_VOTOS_ANULADOS_APU_SEP",
    ]

}

CANDIDATE_ASSETS = [
    "DATA_GERACAO",
    "HORA_GERACAO",
    "ANO_ELEICAO",
    "DESCRICAO_ELEICAO",
    "SIGLA_UF",
    "SEQUENCIAL_CANDIDATO",
    "CD_TIPO_BEM_CANDIDATO",
    "DS_TIPO_BEM_CANDIDATO",
    "DETALHE_BEM",
    "VALOR_BEM",
    "DATA_ULTIMA_ATUALIZACAO",
    "HORA_ULTIMA_ATUALIZACAO",
    "ID_CANDIDATO",
    "SIGLA_UE",
    "DESCRICAO_UE",
    "CODIGO_CARGO",
    "DESCRICAO_CARGO",
    "NUMERO_PARTIDO",
    "SIGLA_PARTIDO",
    "NOME_CANDIDATO",
    "NUMERO_CANDIDATO",
    "CPF_CANDIDATO",
    "NOME_URNA_CANDIDATO",
    "COD_SITUACAO_CANDIDATURA",
    "DES_SITUACAO_CANDIDATURA",
    "NOME_PARTIDO",
    "CODIGO_LEGENDA",
    "SIGLA_LEGENDA",
    "COMPOSICAO_LEGENDA",
    "NOME_COLIGACAO",
    "CODIGO_OCUPACAO",
    "DESCRICAO_OCUPACAO",
    "DATA_NASCIMENTO",
    "NUM_TITULO_ELEITORAL_CANDIDATO",
    "IDADE_DATA_ELEICAO",
    "CODIGO_SEXO",
    "DESCRICAO_SEXO",
    "COD_GRAU_INSTRUCAO",
    "DESCRICAO_GRAU_INSTRUCAO",
    "CODIGO_ESTADO_CIVIL",
    "DESCRICAO_ESTADO_CIVIL",
    "CODIGO_COR_RACA",
    "DESCRICAO_COR_RACA",
    "CODIGO_NACIONALIDADE",
    "DESCRICAO_NACIONALIDADE",
    "SIGLA_UF_NASCIMENTO",
    "CODIGO_MUNICIPIO_NASCIMENTO",
    "NOME_MUNICIPIO_NASCIMENTO",
    "DESPESA_MAX_CAMPANHA",
    "EMAIL_CANDIDATO"
]

SECRETARIES = [
    "STATUS",
    "NOME_SECRETARIO",
    "RG",
    "SEXO",
    "NOME_MUNICIPIO_NASCIMENTO",
    "UF_NASCIMENTO",
    "CARGO",
    "ORGAO_OCUPADO",
    "UF_ORGAO_OCUPADO",
    "COD_GRAU_INSTRUCAO",
    "DESCRICAO_GRAU_INSTRUCAO",
    "CURSO_MESTRADO",
    "CURSO_DOUTORADO",
    "JA_ERA_FUNCIONARIO_PUBLICO",
    "NIVEL_DE_GOVERNO",
    "TRABALHAVA_NA_SECRETARIA_NO_MOMENTO_DA_NOMEACAO",
    "ORGAO_EM_QUE_TRABALHAVA",
    "ANO_INGRESSO_ORGAO",
    "MES_INGRESSO_ORGAO",
    "PROFISSAO_ANTES_DE_NOMEADO",
    "UF",
    "ID_SECRETARIO",
    "CPF",
    "TITULO_DE_ELEITOR",
    "ORGAO_NOME",
    "ID_CARGO",
    "ID_ORGAO",
    "DATA_ASSUMIU",
    "DATA_DEIXOU",
    "MOTIVO_SAIDA",
    "ORIGEM_FILIACAO",
    "SIGLA_PARTIDO",
    "NOME_PARTIDO",
    "CODIGO_MUNICIPIO",
    "NOME_MUNICIPIO",
    "RACA_RAIS",
    "DATA_NASCIMENTO"
]
